# Stage 1: Base image with system dependencies
FROM nvidia/cuda:12.9.1-devel-ubuntu24.04 AS base
# FROM nvcr.io/nvidia/pytorch:24.10-py3 AS base

# Set environment variables
ENV FORCE_CUDA="1" 
ENV TZ=Europe/Madrid

# Set timezone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Obtain the UID and GID of the current user
ARG USER
ARG USER_ID
ARG USER_GID

# Remove default user present in ubuntu 24
RUN userdel -r ubuntu

RUN groupadd -g $USER_GID $USER \
    && useradd --uid $USER_ID --gid $USER_GID -m $USER \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USER \
    && chmod 0440 /etc/sudoers.d/$USER

# Install system packages
RUN apt-get update && apt-get install -y \
    mesa-utils \
    libglapi-mesa \
    libqt5gui5 \
    build-essential \
    cmake \
    git \
    curl \
    ca-certificates \
    python3-dev \
    python-is-python3 \
    python3-pip \
    python3-setuptools \
    wget \
    figlet \
    jupyter \
    && rm -rf /var/lib/apt/lists/*

# Install UV
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
ENV UV_LINK_MODE=copy


# Set the user
ARG USER
USER $USER

# Disable Jupyter authentication
# RUN jupyter notebook --generate-config
# RUN echo "c.NotebookApp.token = ''" >> /home/$USER/.jupyter/jupyter_notebook_config.py
# RUN echo "c.NotebookApp.password = ''" >> /home/$USER/.jupyter/jupyter_notebook_config.py

# Set working directories
WORKDIR /home/$USER/Datasets
WORKDIR /home/$USER/workspace

# Set custom commands, aliases, and environment variables
ENV USER=$USER
RUN echo "alias INSTALL_OPS=\"cd /home/$USER/workspace && uv pip install tgrip/ops/defattn/ --no-build-isolation --link-mode=copy &&   uv pip install tgrip/ops/gs/ --no-build-isolation --link-mode=copy\"" >> /home/$USER/.bashrc

# Change terminal color
ENV TERM=xterm-256color
RUN echo "PS1='\[\e[91m\]\u\[\e[0m\]@\[\e[93m\]\h\[\e[0m\]:\[\e[35m\]\w\[\e[0m\] > '" >> ~/.bashrc
RUN echo "source ~/.bashrc" >> ~/.bash_profile

# Entrypoint
ENTRYPOINT [ "docker/entrypoint.sh" ]
# ENTRYPOINT [ "/bin/bash", "-l", "-c"  ]