wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  id: 1621fv64
  anonymous: null 
  project: "bevpredformer"
  log_model: False 
  prefix: ""
  group: ""
  tags: []
  job_type: ""

  save_dir: ${hydra:run.dir}
  name: effvit_SpUnet_2TripletTST_scale05_shortrange # ${model.name}
  version: ''
  offline: False

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  log_graph: False
  prefix: ""
  save_dir: ${hydra:run.dir}
  default_hp_metric: False
  name: tb_logs