defaults:
  - _self_

_target_: tgrip.models.text_conditioner.CASemanticFuser

embed_dim: 384 # text encoder output dimension
bev_dim: ${model.net.out_c.query_gen}
num_heads: 8
mlp_dim: 256
past_frames: ${model.net.in_seq_len}
projector_layers: 3

