defaults:
  - _self_

_target_: tgrip.models.heads.SemanticHead

bev_dim: ${model.net.out_c.autoencoder}
past_frames: ${model.net.in_seq_len}
text_dim: 512
hidden_dim: 1024
n_hidden_layers: 2
dropout: 0.1
